changelog:
  exclude:
    labels:
      - ignore-for-release
    # authors:
    #   - octocat
  categories:
    - title: Changelog 📒
      labels:
        - enhancement
        - documentation
        - bug
        - test
    # - title: Exciting New Features 🎉
    #   labels:
    #     - Semver-Minor
    #     - enhancement
    - title: Other Changes
      labels:
        - "*"