name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  COVERALLS: true

jobs:
  all_tests_suite:
    name: All Tests Suite
    runs-on: ubuntu-latest
    container:
      image: juliojimenez/ros:latest

    services: 
      clickhouse:
        image: clickhouse/clickhouse-server
        ports:
          - 8123:8123
        options: --ulimit nofile=262144:262144
      
    steps:
      - name: Do the things
        run: |
          ros -e '(ql:quickload :clickhouse)'
          ros -e '(ql:quickload :clickhouse-test)'
          ros -e '(coveralls:with-coveralls () (asdf:test-system :clickhouse))'
