name: CRITIC

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  critic:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      QUICKLISP_DIST: quicklisp
      LISP: sbcl-bin

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Common Lisp Environment
      uses: 40ants/setup-lisp@v2
      with:
        asdf-system: "clickhouse"

    - name: Change dist to Ultralisp
      run: echo 'dist ultralisp http://dist.ultralisp.org' > qlfile
      shell: bash

    - name: Specify Dependencies in QLFile
      run: |
        echo 'ultralisp 40ants-critic https://github.com/40ants/40ants-critic.git' >> qlfile
        echo 'ultralisp eclector https://github.com/s-expressionists/Eclector.git' >> qlfile
      shell: bash

    - name: Install Dependencies with Qlot
      run: |
        qlot update || qlot update
        qlot install
      shell: bash

    - name: Install LISP-CRITIC Wrapper
      run: qlot exec ros install 40ants-critic
      shell: bash

    - name: Run Critic for "clickhouse" system
      run: qlot exec lisp-critic clickhouse
      shell: bash
